server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}
  rabbitmq:
    host: 192.168.88.128
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated # 开启生产者确认（correlated 表示回调返回消息ID和确认结果）
    publisher-returns: true # 开启消息返回机制（当消息无法路由到队列时，回调通知生产者）
    cache:
      channel:
        size: 50  # 通道池大小，建议大于消费者并发数
      connection:
        mode: channel # 使用通道池
    listener:
      simple:
        acknowledge-mode: manual # 手动确认（manual），可选 auto（自动）、none（不确认），默认时auto，消费者接收消息后立刻确认
        retry:
          enabled: true #开启消费者重试
          max-attempts: 3 #最大重试次数
          initial-interval: 1000 #初始重试时间间隔（1s)
          multiplier: 2 # 重试时间间隔倍数
        default-requeue-rejected: false #重试失败后，不重回原队列，直接死信
        concurrency: 50 #消费者并发数，与生产者匹配
        max-concurrency: 100  # 消费者最大并发数



mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity    # 全局配置文件中的别名
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
        utils: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: "mild jam"
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称【在前端进行设置，需要与前端协调】
    admin-token-name: token

  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
